# EventialsBungee config file

# TODO: Cross-server mail, 

#--------------------------------------#
#            Miscellaneous             #
#--------------------------------------#
rejoin-last-server: true
global-join-message: true #Perm: evbungee.silentjoin
global-quit-message: true #Perm: evbungee.silentquit
mail-server-name: '@Console,console,server'
mail-admin-name: '@Admin,admin,owner'
mail-all-name: '@a,all,everyone'

#--------------------------------------#
#             Mail System              #
#--------------------------------------#
enable-command-mail: true
command-mail: ['newmail', 'mailbox']
mail-read-aliases: ['read', 'inbox', 'received'], 'in', 'r'] #or /mail read
mail-sent-aliases: ['sent', 'outgoing', 'out']
mail-send-aliases: ['send', 'to', 's'] #or /mail <name> <msg>
#Permissions:
#eventials.mail.send
#eventials.mail.unsend
#eventials.mail.block, eventials.mail.block.admin, eventials.mail.block.server, eventials.mail.block.proxy
#eventials.mail.to.admin, eventials.mail.to.server, eventials.mail.to.proxy
#eventials.mail.as.admin, eventials.mail.as.server, eventials.mail.as.proxy, eventials.mail.as.player

#--------------------------------------#
#           Utility Commands           #
#--------------------------------------#
enable-command-teleport: true
command-teleport: ['tp-server', 'server-tp', 'tpserver']

server-aliases:
   Alternate: ['alt','altc','altcraft','alternatecraft','old','oldw','oldworld','flat','flatlands']
   NewWorld: ['new','neww','mysterypeaks','newland']
   Torncraft: ['tc','torn']
   Testcraft: ['test']
   Hardcore: ['hc','hard','hardc']
   MosherMiners: ['mosh','moshpit']

#--------------------------------------#
#          PingManager config          #
#--------------------------------------#
custom-ping: true

# Use SUM for sum of players across all servers
# Use SERVER to only show count for current server
# Example:
# max-player-count: 'sum * 2', online-player-count: 'sum - server'
max-player-count: '25'
online-player-count: 'sum'
hover-message: |
   This is a test &9lol
   Please do not panic
   &7I &llike&f fries!






#--------------------------------------#
#       BungeeChat config UNUSED       #
#--------------------------------------#
# you can add custom regular expressions here
regex:
# make any pasted links clickable for convenience
    - search: '(?<link>(?:(https?)://)?([-\w_\.]{2,}\.[a-z]{2,4})(/\S*)?)'
      replace: "[url]${link}[/url]"
# shows link target in tooltip for security reasons (only if link target differs from shown text)
    - search: '(?i)\[(?:url|command)=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*))\]'
      replace: "[hover=&b${cmd}]$0"
    - search: '(?i)\[/(?:url|command)\]'
      replace: "$0[/hover]"
# if players write commands in chat like ./command, make them clickable + remove the dot
    - search: '(?i)^\.(?<cmd>/.{2,})'
      replace: "[suggest]${cmd}[/suggest]"
# underline clickable things
    - search: '(?i)(?=(\[(?:url|command|suggest)(?:=(?<cmd>(?:(?:[^]\[]*)\[(?:[^]\[]*)\])*(?:[^]\[]*)))?\]))'
      replace: "[u]"
    - search: '(?i)\[/(?:url|command|suggest)\]'
      replace: "$0[/u]"